name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天零点更新
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      actions: read    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: XMURCSVision
          base: header, activity, community, repositories, metadata
          template: classic
          config_timezone: Asia/Shanghai
          filename: profile/stats.svg
                    
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          
          plugin_achievements: yes
          plugin_achievements_threshold: X    
          plugin_achievements_limit: 10          
          plugin_achievements_display: compact   
          

