name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天零点更新
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: XMURCSVision
          base: header, activity, community, repositories, metadata
          template: classic
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage 
          plugin_streak: yes
          plugin_streak_days: true 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year 
