name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天零点更新
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      actions: read    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: XMURCSVision
          base: header, activity, community, repositories, metadata
          template: classic
          config_timezone: Asia/Shanghai
          filename: profile/stats.svg
          
          plugin_lines: yes
          
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          
          plugin_streak: yes
          plugin_streak_days: true 
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_isocalendar_ext: yes

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_achievements: yes
          plugin_achievements_threshold: D       
          plugin_achievements_limit: 10          
          plugin_achievements_display: compact   
          

