name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天零点更新
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
      actions: read    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: XMURCSVision
          base: header, activity, community, repositories, metadata
          template: classic
          config_timezone: Asia/Shanghai
          filename: profile/img/base.svg
          
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: XMURCSVision
          base: ""
          template: classic
          config_timezone: Asia/Shanghai
          filename: profile/img/languages.svg
                    
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 0
          
